namespace libMBIN.NMS.Toolkit
{
    [NMS(GUID = 0xD0F7551B69A9DCD, NameHash = 0xCF97645F)]
    public class TkMaterialFxFlags : NMSTemplate
    {
        // size: 0x40
        public enum MaterialFxFlagEnum : uint {
            _X01_DIFFUSEMAP,
            _X02_SKINNED,
            _X03_NORMALMAP,
            _X04_FEATURESMAP,
            _X05_INVERT_ALPHA,
            _X06_BRIGHT_EDGE,
            _X07_UNLIT,
            _X08_REFLECTIVE,
            _X09_TRANSPARENT,
            _X10_NORECEIVESHADOW,
            _X11_ALPHACUTOUT,
            _X12_BATCHED_BILLBOARD,
            _X13_UVANIMATION,
            _X14_UVSCROLL,
            _X15_WIND,
            _X16_DIFFUSE2MAP,
            _X17_DOUBLESIDED_KEEP_NORMALS,
            _X18_UVTILES,
            _X19_BILLBOARD,
            _X20_PARALLAXMAP,
            _X21_VERTEXCOLOUR,
            _X22_TRANSPARENT_SCALAR,
            _X23_TRANSLUCENT,
            _X24_AOMAP,
            _X25_ROUGHNESS_MASK,
            _X26_IMAGE_BASED_LIGHTING,
            _X27_VBTANGENT,
            _X28_VBSKINNED,
            _X29_VBCOLOUR,
            _X30_REFRACTION,
            _X31_DISPLACEMENT,
            _X32_REFRACTION_MASK,
            _X33_SHELLS,
            _X34_GLOW,
            _X35_GLOW_MASK,
            _X36_DOUBLESIDED,
            _X37_EXPLICIT_MOTION_VECTORS,
            _X38_BENT_NORMALS,
            _X39_METALLIC_MASK,
            _X40_SUBSURFACE_MASK,
            _X41_REFLECTANCE_MASK,
            _X42_DETAIL_NORMAL,
            _X43_NORMAL_TILING,
            _X44_IMPOSTER,
            _X45_VERTEX_BLEND,
            _X46_BILLBOARD_AT,
            _X47_REFLECTION_PROBE,
            _X48_WARPED_DIFFUSE_LIGHTING,
            _X49_DISABLE_AMBIENT,
            _X50_DISABLE_POSTPROCESS,
            _X51_DECAL_DIFFUSE,
            _X52_DECAL_NORMAL,
            _X53_COLOURISABLE,
            _X54_COLOURMASK,
            _X55_MULTITEXTURE,
            _X56_MATCH_GROUND,
            _X57_VERTEXALPHA_AO,
            _X58_USE_CENTRAL_NORMAL,
            _X59_BIASED_REACTIVITY,
            _X60_ACUTE_ANGLE_FADE,
            _X61_CLAMP_AMBIENT,
            _X62_DETAIL_ALPHACUTOUT,
            _X63_DISSOLVE,
            _X64_RESERVED_FLAG_FOR_EARLY_Z_PATCHING_DO_NOT_USE,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public MaterialFxFlagEnum MaterialFxFlag;
    }
}
