namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x40BD81220B73F73E, NameHash = 0xBADBD713)]
    public class GcQuickMenuActions : NMSTemplate
    {
        // size: 0x3C
        public enum QuickMenuActionsEnum : uint {
            None,
            CallFreighter,
            DismissFreighter,
            SummonNexus,
            CallShip,
            CallSquadron,
            SummonVehicleSubMenu,
            SummonBuggy,
            SummonBike,
            SummonTruck,
            SummonWheeledBike,
            SummonHovercraft,
            SummonSubmarine,
            SummonMech,
            VehicleAIToggle,
            VehicleScan,
            VehicleScanSelect,
            VehicleRestartRace,
            Torch,
            GalaxyMap,
            PhotoMode,
            ChargeMenu,
            Charge,
            ChargeSubMenu,
            Repair,
            BuildMenu,
            CommunicatorReceive,
            CommunicatorInitiate,
            ThirdPersonCharacter,
            ThirdPersonShip,
            ThirdPersonVehicle,
            EconomyScan,
            EmoteMenu,
            Emote,
            UtilitySubMenu,
            SummonSubMenu,
            SummonShipSubMenu,
            ChangeSecondaryWeaponMenu,
            ChangeSecondaryWeapon,
            ChooseCreatureFoodMenu,
            ChooseCreatureFood,
            EmergencyWarp,
            SwapMultitool,
            SwapMultitoolSubMenu,
            CreatureSubMenu,
            SummonPet,
            SummonPetSubMenu,
            WarpToNexus,
            PetUI,
            ByteBeatSubMenu,
            ByteBeatPlay,
            ByteBeatStop,
            ByteBeatLibrary,
            ReportBase,
            CargoShield,
            CallRocket,
            SummonSkiff,
            FishBaitBox,
            FoodUnit,
            Invalid,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public QuickMenuActionsEnum QuickMenuActions;
    }
}
